from pathlib import Path
import re

from altium_cruncher.altium_cruncher_cmd_clean import _write_config_template
from altium_cruncher.altium_pcblib_clean import (
    DEFAULT_PCBLIB_CLEAN_CONFIG_FILENAME,
    PcbLibCleanConfig,
    find_workspace_pcblib_clean_config_path,
)
from altium_cruncher.config_json import load_json_config


def _assert_jsonc_properties_are_commented(text: str) -> None:
    lines = text.splitlines()
    property_pattern = re.compile(r'^\s+"[^"]+":')
    failures: list[str] = []
    for index, line in enumerate(lines):
        if property_pattern.match(line) is None:
            continue
        previous = index - 1
        while previous >= 0 and not lines[previous].strip():
            previous -= 1
        if previous < 0 or not lines[previous].lstrip().startswith("//"):
            failures.append(line.strip())
    assert failures == []


def test_find_workspace_pcblib_clean_config_path_from_project_child(tmp_path: Path) -> None:
    config_dir = tmp_path / "config"
    config_dir.mkdir()
    (config_dir / "workspace.json").write_text("{}", encoding="utf-8")

    child_dir = tmp_path / "project" / "board"
    child_dir.mkdir(parents=True)

    assert find_workspace_pcblib_clean_config_path(start_dir=child_dir, env={}) == (
        config_dir / DEFAULT_PCBLIB_CLEAN_CONFIG_FILENAME
    )


def test_find_workspace_pcblib_clean_config_path_from_config_dir(tmp_path: Path) -> None:
    config_dir = tmp_path / "config"
    config_dir.mkdir()
    (config_dir / "workspace.json").write_text("{}", encoding="utf-8")

    assert find_workspace_pcblib_clean_config_path(start_dir=config_dir, env={}) == (
        config_dir / DEFAULT_PCBLIB_CLEAN_CONFIG_FILENAME
    )


def test_find_workspace_pcblib_clean_config_path_from_env(tmp_path: Path) -> None:
    workspace_dir = tmp_path / "workspace"

    assert find_workspace_pcblib_clean_config_path(
        env={"ALX_HW_WORKSPACE": str(workspace_dir)}
    ) == (workspace_dir / "config" / DEFAULT_PCBLIB_CLEAN_CONFIG_FILENAME).resolve()


def test_pcblib_clean_config_loader_accepts_jsonc(tmp_path: Path) -> None:
    """Load editable PcbLib clean configs with comments and trailing commas."""
    config_path = tmp_path / DEFAULT_PCBLIB_CLEAN_CONFIG_FILENAME
    config_path.write_text(
        """
        {
          "schema": "wn.altium.pcblib.clean.config.v1",
          "profile": "default",
          // comment out sections while tuning cleanup rules
        }
        """,
        encoding="utf-8",
    )

    config = PcbLibCleanConfig.from_file(config_path)

    assert config.profile == "default"


def test_clean_config_templates_are_commented_jsonc(tmp_path: Path) -> None:
    """Generated clean templates should guide users and remain machine-readable."""
    schematic_config = tmp_path / "altium-clean.json"
    pcblib_config = tmp_path / DEFAULT_PCBLIB_CLEAN_CONFIG_FILENAME

    _write_config_template(schematic_config, suffix=".schdoc")
    _write_config_template(pcblib_config, suffix=".pcblib")

    schematic_text = schematic_config.read_text(encoding="utf-8")
    pcblib_text = pcblib_config.read_text(encoding="utf-8")

    assert "// Generated by altium-cruncher clean." in schematic_text
    assert "// Schematic clean config for .SchDoc, .SchLib, and .PrjPcb inputs." in schematic_text
    assert "// Altium font family name to apply." in schematic_text
    assert "// Rectangle outline color." in schematic_text
    assert "// PcbLib clean config for footprint-library cleanup." in pcblib_text
    assert "// Text matching mode: all, regex, contains, or exact." in pcblib_text
    assert "// Keep regions used to represent custom pads." in pcblib_text
    _assert_jsonc_properties_are_commented(schematic_text)
    _assert_jsonc_properties_are_commented(pcblib_text)
    assert load_json_config(schematic_config)["schema"] == "wn.altium.clean.config.v1"
    assert load_json_config(pcblib_config)["schema"] == "wn.altium.pcblib.clean.config.v1"
