"""impedance-doc command for altium_cruncher.

Per-copper-layer controlled-impedance routing documentation (differential +
single-ended), rendered natively to SVG/HTML/PNG/PDF with a commented JSONC
config as the editable escape hatch.
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path

from altium_cruncher.altium_cruncher_common import (
    _resolve_output_dir,
    find_prjpcb_in_cwd,
)
from altium_cruncher.altium_cruncher_pcb_workflow import (
    iter_pcb_render_inputs,
    load_design_for_pcb_input,
)
from altium_cruncher.altium_cruncher_impedance_doc import (
    CONFIG_FILENAME,
    apply_config,
    discover_impedance_classes,
    group_by_impedance,
    load_config,
    render_config_jsonc,
    render_impedance_doc,
)

log = logging.getLogger(__name__)

_DEFAULT_MIN_LEN = 10.0


def cmd_impedance_doc(args: argparse.Namespace) -> int:
    """Render per-layer controlled-impedance routing documentation."""
    input_file = _resolve_input(args)
    if input_file is None:
        return 1

    try:
        design, _source = load_design_for_pcb_input(
            input_file, project_context=getattr(args, "project_context", "auto")
        )
        render_inputs = iter_pcb_render_inputs(
            design, pcbdoc_selector=getattr(args, "pcbdoc", None)
        )
    except Exception as exc:
        log.error("Failed to load %s: %s", input_file.name, exc)
        return 1

    base_output = _resolve_output_dir(args.output, "impedance-doc")
    config_override = Path(args.config).resolve() if args.config else None

    any_groups = False
    for render_input in render_inputs:
        pcbdoc = render_input.pcbdoc
        out_dir = base_output / render_input.board_key
        out_dir.mkdir(parents=True, exist_ok=True)
        config_path = config_override or (out_dir / CONFIG_FILENAME)

        # First detect at the default min length so an autogenerated config can
        # list every group; then honor the config's own min length on render.
        groups = group_by_impedance(
            discover_impedance_classes(pcbdoc, _DEFAULT_MIN_LEN)
        )
        if not groups:
            log.warning(
                "No controlled-impedance classes with routed copper in %s",
                render_input.board_key,
            )
            continue
        any_groups = True

        if not config_path.exists():
            config_path.write_text(
                render_config_jsonc(render_input.pcb_path.as_posix(), groups),
                encoding="utf-8",
            )
            log.info("Wrote config: %s", config_path)
        config = load_config(config_path)

        min_len = float(
            config.get("view", {}).get("min_routing_length_mils", _DEFAULT_MIN_LEN)
        )
        groups = group_by_impedance(discover_impedance_classes(pcbdoc, min_len))
        apply_config(groups, config)

        page_title = (
            config.get("style", {}).get("title")
            or f"{render_input.pcb_path.stem} - controlled-impedance routing"
        )
        log.info("%s: %d impedance group(s)", render_input.board_key, len(groups))
        for g in groups:
            log.info(
                "  %s [%s]: %d class(es), %d net(s), %d routed layer(s)",
                g.title, g.kind, len(g.classes), len(g.nets), len(g.layers),
            )

        result = render_impedance_doc(
            pcbdoc,
            render_input.project_parameters,
            groups,
            config,
            out_dir,
            page_title,
        )
        log.info(
            "%s: wrote %d layer page(s) to %s",
            render_input.board_key, len(result.svg_pages), out_dir / "svg",
        )

    return 0 if any_groups else 1


def _resolve_input(args: argparse.Namespace) -> Path | None:
    if args.file:
        input_file = Path(args.file).resolve()
        if not input_file.exists():
            log.error("File not found: %s", input_file)
            return None
    else:
        input_file = find_prjpcb_in_cwd()
        if input_file is None:
            log.error("No file specified and no .PrjPcb found in current directory")
            return None
        log.info("Auto-detected project: %s", input_file.name)
    if input_file.suffix.lower() not in {".pcbdoc", ".prjpcb"}:
        log.error("Unsupported impedance-doc input type: %s", input_file.suffix)
        return None
    return input_file


def register_parser(
    subparsers: argparse._SubParsersAction,
) -> argparse.ArgumentParser:
    """Register the impedance-doc command parser."""
    parser = subparsers.add_parser(
        "impedance-doc",
        help="per-layer controlled-impedance routing documentation (SVG/HTML/PNG/PDF)",
        description=(
            "Render per-copper-layer review pages showing where each "
            "controlled-impedance class routes, with the target impedance and "
            "single-ended / differential kind labeled. Covers differential-pair "
            "classes and single-ended net classes. Autogenerates a commented "
            "JSONC config (impedance-doc.config) as the editable escape hatch."
        ),
        epilog=(
            "Examples:\n"
            "  altium-cruncher impedance-doc board.PcbDoc\n"
            "  altium-cruncher impedance-doc project.PrjPcb -o output/impedance\n"
            "  altium-cruncher impedance-doc board.PcbDoc --config impedance-doc.config"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "file",
        nargs="?",
        help="PcbDoc or PrjPcb file (optional if PrjPcb in CWD)",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="output directory (default: ./output/impedance-doc)",
    )
    parser.add_argument(
        "--config",
        type=Path,
        help="impedance-doc.config (JSONC) to use; autogenerated per board when omitted",
    )
    parser.add_argument(
        "--pcbdoc",
        help="select a single PcbDoc by name/stem when the project has several",
    )
    parser.add_argument(
        "--project-context",
        choices=("auto", "none", "schematic"),
        default="auto",
        help="how much project context to load for a PcbDoc input (default: auto)",
    )
    parser.set_defaults(handler=cmd_impedance_doc)
    return parser
